export enum ErrorMesagge {
    required = 'Esta información es Requerida',
    minLength = 'No ha alcanzado la longitud mínima requerida',
    maxLength = 'Ha sobrepasado la longitud máxima permitida',
    validCI = 'Número de Carnet de Identidad incorrecto',
    usedCI = 'Número de Carnet de Identidad en Uso',
    email = 'Correo electrónico incorrecto',
    pattern = 'Este campo sólo admite Números',
    alphanumeric = 'Este campo sólo admite caracteres alfanuméricos',
    extension = 'Extensión de Fichero no Permitida (Formatos permitidos: .pdf .png .jpg)',
    nonZero = 'Solo se permiten números mayores que 0',
    minSelectedCheckboxes = 'Debe seleccionar al menos una opción',
    requiredPass = 'La Contraseña es Requerida',
    strongPass = 'La Contraseña no cumple con los estándares de seguridad',
    confirmPass = 'La Contraseña y su Confirmación deben coincidir',
    oldPass = 'La Contraseña actual es incorrecta',
    usedUser = 'El nombre de usuario está en uso',
    usedPass = 'La Contraseña ha sido utilizada recientemente',
    text = 'No se permiten caracteres especiales',
    generic = 'Caracter no permitido',
}
