export const environment = {
  production: true,
  APP_NAME: 'ONIE - Oficina Nacional de Inspección Estatal',
  APP_VERSION: '1.0.0',
  INC_NAME: 'Empresa de Servicios Automatizados - Alimatic',
  EXP_PASS: 5,
  MAX_ATTEMPTS: 3,
  docsUrl: 'https://onie2.alinet.cu/',
  baseUrl: 'https://onie2.alinet.cu/api/',
  authUrl: 'https://onie2.alinet.cu/api/auth',
  userUrl: 'https://onie2.alinet.cu/api/users',
  signUpUrl: 'https://onie2.alinet.cu/api/users',
  municipaliteUrl: 'https://onie2.alinet.cu/api/utils/municipalites',
  provinceUrl: 'https://onie2.alinet.cu/api/utils/provinces',
  fisheryUrl: 'https://onie2.alinet.cu/api/utils/fishery',
  fisheryCraftUrl: 'https://onie2.alinet.cu/api/utils/fisherycraft',
  requestUrl: 'https://onie2.alinet.cu/api/request',
  requestAPUrl: 'https://onie2.alinet.cu/api/request-aquaculture-private',
  requestASUrl: 'https://onie2.alinet.cu/api/request-aquaculture-state',
  requestPPUrl: 'https://onie2.alinet.cu/api/request-platform/private',
  requestPSUrl: 'https://onie2.alinet.cu/api/request-platform/state',
  licenseUrl: 'https://onie2.alinet.cu/api/license',
  licenseAPUrl: 'https://onie2.alinet.cu/api/license/aquaculture-private',
  licenseASUrl: 'https://onie2.alinet.cu/api/license/aquaculture-state',
  licensePPUrl: 'https://onie2.alinet.cu/api/license/platform-private',
  licensePSUrl: 'https://onie2.alinet.cu/api/license/platform-state',
  penaltyUrl: 'https://onie2.alinet.cu/api/penalty',
  offenderUrl: 'https://onie2.alinet.cu/api/penalty/offender',

};
